//*
// The NEVR server RPC protocol for games and apps.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: apigrpc/apigrpc.proto

package apigrpc

import (
	context "context"
	api "github.com/echotools/nevr-common/v3/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Nevr_ListServers_FullMethodName = "/nevr.apigrpc.Nevr/ListServers"
)

// NevrClient is the client API for Nevr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// The Nevr RPC protocol service built with GRPC.
type NevrClient interface {
	// List game servers.
	ListServers(ctx context.Context, in *api.ListGuildGameServersRequest, opts ...grpc.CallOption) (*api.GuildGameServerList, error)
}

type nevrClient struct {
	cc grpc.ClientConnInterface
}

func NewNevrClient(cc grpc.ClientConnInterface) NevrClient {
	return &nevrClient{cc}
}

func (c *nevrClient) ListServers(ctx context.Context, in *api.ListGuildGameServersRequest, opts ...grpc.CallOption) (*api.GuildGameServerList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.GuildGameServerList)
	err := c.cc.Invoke(ctx, Nevr_ListServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NevrServer is the server API for Nevr service.
// All implementations should embed UnimplementedNevrServer
// for forward compatibility.
//
// *
// The Nevr RPC protocol service built with GRPC.
type NevrServer interface {
	// List game servers.
	ListServers(context.Context, *api.ListGuildGameServersRequest) (*api.GuildGameServerList, error)
}

// UnimplementedNevrServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNevrServer struct{}

func (UnimplementedNevrServer) ListServers(context.Context, *api.ListGuildGameServersRequest) (*api.GuildGameServerList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServers not implemented")
}
func (UnimplementedNevrServer) testEmbeddedByValue() {}

// UnsafeNevrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NevrServer will
// result in compilation errors.
type UnsafeNevrServer interface {
	mustEmbedUnimplementedNevrServer()
}

func RegisterNevrServer(s grpc.ServiceRegistrar, srv NevrServer) {
	// If the following call pancis, it indicates UnimplementedNevrServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Nevr_ServiceDesc, srv)
}

func _Nevr_ListServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.ListGuildGameServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NevrServer).ListServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nevr_ListServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NevrServer).ListServers(ctx, req.(*api.ListGuildGameServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Nevr_ServiceDesc is the grpc.ServiceDesc for Nevr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Nevr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nevr.apigrpc.Nevr",
	HandlerType: (*NevrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListServers",
			Handler:    _Nevr_ListServers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apigrpc/apigrpc.proto",
}
