//*
// The NEVR server RPC protocol for games and apps.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: apigrpc/apigrpc.proto

package apigrpc

import (
	api "github.com/echotools/nevr-common/v3/api"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_apigrpc_apigrpc_proto protoreflect.FileDescriptor

const file_apigrpc_apigrpc_proto_rawDesc = "" +
	"\n" +
	"\x15apigrpc/apigrpc.proto\x12\fnevr.apigrpc\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\rapi/api.proto2\x85\x01\n" +
	"\x04Nevr\x12}\n" +
	"\vListServers\x12%.nevr.api.ListGuildGameServersRequest\x1a\x1d.nevr.api.GuildGameServerList\"(\x82\xd3\xe4\x93\x02\"\x12 /v2/guild/{guild_id}/gameserversB\xb4\x03\x92A\xc8\x02\x12e\n" +
	"\vNEVR API v2\"Q\n" +
	"\x1fThe NEVR Authors & Contributors\x12!https://github.com/echotools/nevr\x1a\va@sprock.io2\x032.0\x1a\x0e127.0.0.1:7350*\x01\x012\x10application/json:\x10application/jsonZR\n" +
	"\x0f\n" +
	"\tBasicAuth\x12\x02\b\x01\n" +
	" \n" +
	"\tBearerJwt\x12\x13\b\x02\x1a\rAuthorization \x02\n" +
	"\x1d\n" +
	"\vHttpKeyAuth\x12\x0e\b\x02\x1a\bhttp_key \x02b\x0f\n" +
	"\r\n" +
	"\tBearerJwt\x12\x00rC\n" +
	"\x19NEVR server documentation\x12&https://github.com/echotools/nevr/docs\n" +
	"\x1acom.echotools.nevr.apigrpcB\vNevrApiGrpcP\x01Z+github.com/echotools/nevr-common/v3/apigrpc\xaa\x02\rNevr.Protobufb\x06proto3"

var file_apigrpc_apigrpc_proto_goTypes = []any{
	(*api.ListGuildGameServersRequest)(nil), // 0: nevr.api.ListGuildGameServersRequest
	(*api.GuildGameServerList)(nil),         // 1: nevr.api.GuildGameServerList
}
var file_apigrpc_apigrpc_proto_depIdxs = []int32{
	0, // 0: nevr.apigrpc.Nevr.ListServers:input_type -> nevr.api.ListGuildGameServersRequest
	1, // 1: nevr.apigrpc.Nevr.ListServers:output_type -> nevr.api.GuildGameServerList
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apigrpc_apigrpc_proto_init() }
func file_apigrpc_apigrpc_proto_init() {
	if File_apigrpc_apigrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apigrpc_apigrpc_proto_rawDesc), len(file_apigrpc_apigrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apigrpc_apigrpc_proto_goTypes,
		DependencyIndexes: file_apigrpc_apigrpc_proto_depIdxs,
	}.Build()
	File_apigrpc_apigrpc_proto = out.File
	file_apigrpc_apigrpc_proto_goTypes = nil
	file_apigrpc_apigrpc_proto_depIdxs = nil
}
