//*
// The Nevr server RPC protocol for games and apps.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The server session status.
type GuildGameServerList_GuildGameServer_State int32

const (
	// The server is inactive and cannot be connected to.
	GuildGameServerList_GuildGameServer_INACTIVE GuildGameServerList_GuildGameServer_State = 0
	// The session is active and can be connected to.
	GuildGameServerList_GuildGameServer_ACTIVE GuildGameServerList_GuildGameServer_State = 1
	// The session is closed and will be deleted soon.
	GuildGameServerList_GuildGameServer_CLOSED GuildGameServerList_GuildGameServer_State = 2
)

// Enum value maps for GuildGameServerList_GuildGameServer_State.
var (
	GuildGameServerList_GuildGameServer_State_name = map[int32]string{
		0: "INACTIVE",
		1: "ACTIVE",
		2: "CLOSED",
	}
	GuildGameServerList_GuildGameServer_State_value = map[string]int32{
		"INACTIVE": 0,
		"ACTIVE":   1,
		"CLOSED":   2,
	}
)

func (x GuildGameServerList_GuildGameServer_State) Enum() *GuildGameServerList_GuildGameServer_State {
	p := new(GuildGameServerList_GuildGameServer_State)
	*p = x
	return p
}

func (x GuildGameServerList_GuildGameServer_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GuildGameServerList_GuildGameServer_State) Descriptor() protoreflect.EnumDescriptor {
	return file_api_api_proto_enumTypes[0].Descriptor()
}

func (GuildGameServerList_GuildGameServer_State) Type() protoreflect.EnumType {
	return &file_api_api_proto_enumTypes[0]
}

func (x GuildGameServerList_GuildGameServer_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GuildGameServerList_GuildGameServer_State.Descriptor instead.
func (GuildGameServerList_GuildGameServer_State) EnumDescriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2, 0, 0}
}

// List game servers.
type ListServersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Limit the number of returned matches.
	Limit *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Arbitrary label query.
	Query         *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersRequest) Reset() {
	*x = ListServersRequest{}
	mi := &file_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersRequest) ProtoMessage() {}

func (x *ListServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersRequest.ProtoReflect.Descriptor instead.
func (*ListServersRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *ListServersRequest) GetLimit() *wrapperspb.Int32Value {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *ListServersRequest) GetQuery() *wrapperspb.StringValue {
	if x != nil {
		return x.Query
	}
	return nil
}

// List all users that are part of a group.
type ListGuildGameServersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The guild ID to list from.
	GuildId string `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	// Max number of records to return. Between 1 and 100.
	Limit *wrapperspb.Int32Value `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// The game server state to list.
	State *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	// Arbitrary label query.
	Query *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	// An optional next page cursor.
	Cursor        string `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGuildGameServersRequest) Reset() {
	*x = ListGuildGameServersRequest{}
	mi := &file_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGuildGameServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGuildGameServersRequest) ProtoMessage() {}

func (x *ListGuildGameServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGuildGameServersRequest.ProtoReflect.Descriptor instead.
func (*ListGuildGameServersRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *ListGuildGameServersRequest) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *ListGuildGameServersRequest) GetLimit() *wrapperspb.Int32Value {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *ListGuildGameServersRequest) GetState() *wrapperspb.Int32Value {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ListGuildGameServersRequest) GetQuery() *wrapperspb.StringValue {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ListGuildGameServersRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GuildGameServerList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-state pairs.
	GuildServers []*GuildGameServerList_GuildGameServer `protobuf:"bytes,4,rep,name=guild_servers,json=guildServers,proto3" json:"guild_servers,omitempty"`
	// An optional next page cursor.
	Cursor        string `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildGameServerList) Reset() {
	*x = GuildGameServerList{}
	mi := &file_api_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildGameServerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildGameServerList) ProtoMessage() {}

func (x *GuildGameServerList) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildGameServerList.ProtoReflect.Descriptor instead.
func (*GuildGameServerList) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *GuildGameServerList) GetGuildServers() []*GuildGameServerList_GuildGameServer {
	if x != nil {
		return x.GuildServers
	}
	return nil
}

func (x *GuildGameServerList) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// Game Server
type GameServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the server.
	ServerId *wrapperspb.UInt64Value `protobuf:"bytes,10,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// The user ID of the owner of the server.
	OperatorId *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	// The endpoint data used for client connections. (internal_ip:external_ip:port)
	Endpoint *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// The features of the server.
	SupportedFeatures []string `protobuf:"bytes,11,rep,name=supported_features,json=supportedFeatures,proto3" json:"supported_features,omitempty"`
	// The timestep duration in nanoseconds.
	TimestepNanos int32 `protobuf:"varint,3,opt,name=timestep_nanos,json=timestepNanos,proto3" json:"timestep_nanos,omitempty"`
	// Additional information about the server.
	Metadata      map[string]string `protobuf:"bytes,24,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameServer) Reset() {
	*x = GameServer{}
	mi := &file_api_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServer) ProtoMessage() {}

func (x *GameServer) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServer.ProtoReflect.Descriptor instead.
func (*GameServer) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *GameServer) GetServerId() *wrapperspb.UInt64Value {
	if x != nil {
		return x.ServerId
	}
	return nil
}

func (x *GameServer) GetOperatorId() *wrapperspb.StringValue {
	if x != nil {
		return x.OperatorId
	}
	return nil
}

func (x *GameServer) GetEndpoint() *wrapperspb.StringValue {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *GameServer) GetSupportedFeatures() []string {
	if x != nil {
		return x.SupportedFeatures
	}
	return nil
}

func (x *GameServer) GetTimestepNanos() int32 {
	if x != nil {
		return x.TimestepNanos
	}
	return 0
}

func (x *GameServer) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// A single server-state pair.
type GuildGameServerList_GuildGameServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server.
	GameServer *GameServer `protobuf:"bytes,1,opt,name=game_server,json=gameServer,proto3" json:"game_server,omitempty"`
	// The user's relationship to the group.
	State         *wrapperspb.Int32Value `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildGameServerList_GuildGameServer) Reset() {
	*x = GuildGameServerList_GuildGameServer{}
	mi := &file_api_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildGameServerList_GuildGameServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildGameServerList_GuildGameServer) ProtoMessage() {}

func (x *GuildGameServerList_GuildGameServer) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildGameServerList_GuildGameServer.ProtoReflect.Descriptor instead.
func (*GuildGameServerList_GuildGameServer) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GuildGameServerList_GuildGameServer) GetGameServer() *GameServer {
	if x != nil {
		return x.GameServer
	}
	return nil
}

func (x *GuildGameServerList_GuildGameServer) GetState() *wrapperspb.Int32Value {
	if x != nil {
		return x.State
	}
	return nil
}

var File_api_api_proto protoreflect.FileDescriptor

const file_api_api_proto_rawDesc = "" +
	"\n" +
	"\rapi/api.proto\x12\bnevr.api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"{\n" +
	"\x12ListServersRequest\x121\n" +
	"\x05limit\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05limit\x122\n" +
	"\x05query\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x05query\"\xea\x01\n" +
	"\x1bListGuildGameServersRequest\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\tR\aguildId\x121\n" +
	"\x05limit\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05limit\x121\n" +
	"\x05state\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05state\x122\n" +
	"\x05query\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x05query\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\"\xae\x02\n" +
	"\x13GuildGameServerList\x12R\n" +
	"\rguild_servers\x18\x04 \x03(\v2-.nevr.api.GuildGameServerList.GuildGameServerR\fguildServers\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x1a\xaa\x01\n" +
	"\x0fGuildGameServer\x125\n" +
	"\vgame_server\x18\x01 \x01(\v2\x14.nevr.api.GameServerR\n" +
	"gameServer\x121\n" +
	"\x05state\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05state\"-\n" +
	"\x05State\x12\f\n" +
	"\bINACTIVE\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x02\"\x93\x03\n" +
	"\n" +
	"GameServer\x129\n" +
	"\tserver_id\x18\n" +
	" \x01(\v2\x1c.google.protobuf.UInt64ValueR\bserverId\x12=\n" +
	"\voperator_id\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"operatorId\x128\n" +
	"\bendpoint\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\bendpoint\x12-\n" +
	"\x12supported_features\x18\v \x03(\tR\x11supportedFeatures\x12%\n" +
	"\x0etimestep_nanos\x18\x03 \x01(\x05R\rtimestepNanos\x12>\n" +
	"\bmetadata\x18\x18 \x03(\v2\".nevr.api.GameServer.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01Bc\n" +
	"\x1dcom.github.echotools.nevr.apiB\aNevrApiP\x01Z'github.com/echotools/nevr-common/v3/api\xaa\x02\rNevr.Protobufb\x06proto3"

var (
	file_api_api_proto_rawDescOnce sync.Once
	file_api_api_proto_rawDescData []byte
)

func file_api_api_proto_rawDescGZIP() []byte {
	file_api_api_proto_rawDescOnce.Do(func() {
		file_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)))
	})
	return file_api_api_proto_rawDescData
}

var file_api_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_api_proto_goTypes = []any{
	(GuildGameServerList_GuildGameServer_State)(0), // 0: nevr.api.GuildGameServerList.GuildGameServer.State
	(*ListServersRequest)(nil),                     // 1: nevr.api.ListServersRequest
	(*ListGuildGameServersRequest)(nil),            // 2: nevr.api.ListGuildGameServersRequest
	(*GuildGameServerList)(nil),                    // 3: nevr.api.GuildGameServerList
	(*GameServer)(nil),                             // 4: nevr.api.GameServer
	(*GuildGameServerList_GuildGameServer)(nil),    // 5: nevr.api.GuildGameServerList.GuildGameServer
	nil,                            // 6: nevr.api.GameServer.MetadataEntry
	(*wrapperspb.Int32Value)(nil),  // 7: google.protobuf.Int32Value
	(*wrapperspb.StringValue)(nil), // 8: google.protobuf.StringValue
	(*wrapperspb.UInt64Value)(nil), // 9: google.protobuf.UInt64Value
}
var file_api_api_proto_depIdxs = []int32{
	7,  // 0: nevr.api.ListServersRequest.limit:type_name -> google.protobuf.Int32Value
	8,  // 1: nevr.api.ListServersRequest.query:type_name -> google.protobuf.StringValue
	7,  // 2: nevr.api.ListGuildGameServersRequest.limit:type_name -> google.protobuf.Int32Value
	7,  // 3: nevr.api.ListGuildGameServersRequest.state:type_name -> google.protobuf.Int32Value
	8,  // 4: nevr.api.ListGuildGameServersRequest.query:type_name -> google.protobuf.StringValue
	5,  // 5: nevr.api.GuildGameServerList.guild_servers:type_name -> nevr.api.GuildGameServerList.GuildGameServer
	9,  // 6: nevr.api.GameServer.server_id:type_name -> google.protobuf.UInt64Value
	8,  // 7: nevr.api.GameServer.operator_id:type_name -> google.protobuf.StringValue
	8,  // 8: nevr.api.GameServer.endpoint:type_name -> google.protobuf.StringValue
	6,  // 9: nevr.api.GameServer.metadata:type_name -> nevr.api.GameServer.MetadataEntry
	4,  // 10: nevr.api.GuildGameServerList.GuildGameServer.game_server:type_name -> nevr.api.GameServer
	7,  // 11: nevr.api.GuildGameServerList.GuildGameServer.state:type_name -> google.protobuf.Int32Value
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_api_proto_init() }
func file_api_api_proto_init() {
	if File_api_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_api_proto_goTypes,
		DependencyIndexes: file_api_api_proto_depIdxs,
		EnumInfos:         file_api_api_proto_enumTypes,
		MessageInfos:      file_api_api_proto_msgTypes,
	}.Build()
	File_api_api_proto = out.File
	file_api_api_proto_goTypes = nil
	file_api_api_proto_depIdxs = nil
}
