# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nevr_api.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'nevr_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enevr_api.proto\x12\x08nevr.api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x95\x03\n\x13PrepareMatchRequest\x12\x0c\n\x04mode\x18\x01 \x01(\t\x12\x0e\n\x06region\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\t\x12.\n\tteam_size\x18\x04 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12/\n\x0b\x65xpiry_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08owner_id\x18\x06 \x01(\t\x12\x10\n\x08group_id\x18\x07 \x01(\t\x12\x19\n\x11required_features\x18\x08 \x03(\t\x12J\n\x0fteam_alignments\x18\t \x03(\x0b\x32\x31.nevr.api.PrepareMatchRequest.TeamAlignmentsEntry\x12.\n\ttick_rate\x18\n \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x1a\x35\n\x13TeamAlignmentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x63\n\x1d\x63om.github.echotools.nevr.apiB\x07NevrApiP\x01Z\'github.com/echotools/nevr-common/v3/api\xaa\x02\rNevr.Protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nevr_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.github.echotools.nevr.apiB\007NevrApiP\001Z\'github.com/echotools/nevr-common/v3/api\252\002\rNevr.Protobuf'
  _globals['_PREPAREMATCHREQUEST_TEAMALIGNMENTSENTRY']._loaded_options = None
  _globals['_PREPAREMATCHREQUEST_TEAMALIGNMENTSENTRY']._serialized_options = b'8\001'
  _globals['_PREPAREMATCHREQUEST']._serialized_start=94
  _globals['_PREPAREMATCHREQUEST']._serialized_end=499
  _globals['_PREPAREMATCHREQUEST_TEAMALIGNMENTSENTRY']._serialized_start=446
  _globals['_PREPAREMATCHREQUEST_TEAMALIGNMENTSENTRY']._serialized_end=499
# @@protoc_insertion_point(module_scope)
