//*
// The NEVR service RPC protocol for the client, servers, and apps.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: nevr_api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A request to prepare a match for users to join.
type PrepareMatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The match mode.
	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// The region where the match will be prepared (optional).
	Region string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	// The level for the match (optional).
	Level string `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	// The size of each team in the match (optional).
	TeamSize *wrapperspb.Int32Value `protobuf:"bytes,4,opt,name=team_size,json=teamSize,proto3" json:"team_size,omitempty"`
	// The time the match is scheduled to start (optional)
	ExpiryTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expiry_time,json=expiryTime,proto3" json:"expiry_time,omitempty"`
	// The user ID of the user who will own the match (optional).
	OwnerId string `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// The group ID of the guild where the match will be spawned (optional).
	GroupId string `protobuf:"bytes,7,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// The features required for the match (optional).
	RequiredFeatures []string `protobuf:"bytes,8,rep,name=required_features,json=requiredFeatures,proto3" json:"required_features,omitempty"`
	// Mapping user IDs to blue or orange (optional)
	TeamAlignments map[string]string `protobuf:"bytes,9,rep,name=team_alignments,json=teamAlignments,proto3" json:"team_alignments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Tick Rate of the match in Hz (optional)
	TickRate      *wrapperspb.Int32Value `protobuf:"bytes,10,opt,name=tick_rate,json=tickRate,proto3" json:"tick_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMatchRequest) Reset() {
	*x = PrepareMatchRequest{}
	mi := &file_nevr_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMatchRequest) ProtoMessage() {}

func (x *PrepareMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nevr_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMatchRequest.ProtoReflect.Descriptor instead.
func (*PrepareMatchRequest) Descriptor() ([]byte, []int) {
	return file_nevr_api_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareMatchRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *PrepareMatchRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PrepareMatchRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *PrepareMatchRequest) GetTeamSize() *wrapperspb.Int32Value {
	if x != nil {
		return x.TeamSize
	}
	return nil
}

func (x *PrepareMatchRequest) GetExpiryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryTime
	}
	return nil
}

func (x *PrepareMatchRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *PrepareMatchRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *PrepareMatchRequest) GetRequiredFeatures() []string {
	if x != nil {
		return x.RequiredFeatures
	}
	return nil
}

func (x *PrepareMatchRequest) GetTeamAlignments() map[string]string {
	if x != nil {
		return x.TeamAlignments
	}
	return nil
}

func (x *PrepareMatchRequest) GetTickRate() *wrapperspb.Int32Value {
	if x != nil {
		return x.TickRate
	}
	return nil
}

// AccountLookupRequest is a request to look up user accounts by various
// identifiers.
type GetPlayersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Nakama username or Discord username.
	Usernames []string `protobuf:"bytes,1,rep,name=usernames,proto3" json:"usernames,omitempty"`
	// The Nakama user UUIDs.
	UserIds []string `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	// The Discord IDs (snowflakes).
	DiscordIds []string `protobuf:"bytes,3,rep,name=discord_ids,json=discordIds,proto3" json:"discord_ids,omitempty"`
	// The OVR-ORG-123412341234 XPIDs.
	XpIds []string `protobuf:"bytes,4,rep,name=xp_ids,json=xpIds,proto3" json:"xp_ids,omitempty"`
	// The active display names (may be unreliable).
	DisplayNames  []string `protobuf:"bytes,5,rep,name=display_names,json=displayNames,proto3" json:"display_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayersRequest) Reset() {
	*x = GetPlayersRequest{}
	mi := &file_nevr_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayersRequest) ProtoMessage() {}

func (x *GetPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nevr_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayersRequest.ProtoReflect.Descriptor instead.
func (*GetPlayersRequest) Descriptor() ([]byte, []int) {
	return file_nevr_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlayersRequest) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

func (x *GetPlayersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetPlayersRequest) GetDiscordIds() []string {
	if x != nil {
		return x.DiscordIds
	}
	return nil
}

func (x *GetPlayersRequest) GetXpIds() []string {
	if x != nil {
		return x.XpIds
	}
	return nil
}

func (x *GetPlayersRequest) GetDisplayNames() []string {
	if x != nil {
		return x.DisplayNames
	}
	return nil
}

var File_nevr_api_proto protoreflect.FileDescriptor

const file_nevr_api_proto_rawDesc = "" +
	"\n" +
	"\x0enevr_api.proto\x12\bnevr.api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x8a\x04\n" +
	"\x13PrepareMatchRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x128\n" +
	"\tteam_size\x18\x04 \x01(\v2\x1b.google.protobuf.Int32ValueR\bteamSize\x12;\n" +
	"\vexpiry_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryTime\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\tR\aownerId\x12\x19\n" +
	"\bgroup_id\x18\a \x01(\tR\agroupId\x12+\n" +
	"\x11required_features\x18\b \x03(\tR\x10requiredFeatures\x12Z\n" +
	"\x0fteam_alignments\x18\t \x03(\v21.nevr.api.PrepareMatchRequest.TeamAlignmentsEntryR\x0eteamAlignments\x128\n" +
	"\ttick_rate\x18\n" +
	" \x01(\v2\x1b.google.protobuf.Int32ValueR\btickRate\x1aA\n" +
	"\x13TeamAlignmentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa9\x01\n" +
	"\x11GetPlayersRequest\x12\x1c\n" +
	"\tusernames\x18\x01 \x03(\tR\tusernames\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\x12\x1f\n" +
	"\vdiscord_ids\x18\x03 \x03(\tR\n" +
	"discordIds\x12\x15\n" +
	"\x06xp_ids\x18\x04 \x03(\tR\x05xpIds\x12#\n" +
	"\rdisplay_names\x18\x05 \x03(\tR\fdisplayNamesBc\n" +
	"\x1dcom.github.echotools.nevr.apiB\aNevrApiP\x01Z'github.com/echotools/nevr-common/v3/api\xaa\x02\rNevr.Protobufb\x06proto3"

var (
	file_nevr_api_proto_rawDescOnce sync.Once
	file_nevr_api_proto_rawDescData []byte
)

func file_nevr_api_proto_rawDescGZIP() []byte {
	file_nevr_api_proto_rawDescOnce.Do(func() {
		file_nevr_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nevr_api_proto_rawDesc), len(file_nevr_api_proto_rawDesc)))
	})
	return file_nevr_api_proto_rawDescData
}

var file_nevr_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nevr_api_proto_goTypes = []any{
	(*PrepareMatchRequest)(nil),   // 0: nevr.api.PrepareMatchRequest
	(*GetPlayersRequest)(nil),     // 1: nevr.api.GetPlayersRequest
	nil,                           // 2: nevr.api.PrepareMatchRequest.TeamAlignmentsEntry
	(*wrapperspb.Int32Value)(nil), // 3: google.protobuf.Int32Value
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_nevr_api_proto_depIdxs = []int32{
	3, // 0: nevr.api.PrepareMatchRequest.team_size:type_name -> google.protobuf.Int32Value
	4, // 1: nevr.api.PrepareMatchRequest.expiry_time:type_name -> google.protobuf.Timestamp
	2, // 2: nevr.api.PrepareMatchRequest.team_alignments:type_name -> nevr.api.PrepareMatchRequest.TeamAlignmentsEntry
	3, // 3: nevr.api.PrepareMatchRequest.tick_rate:type_name -> google.protobuf.Int32Value
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_nevr_api_proto_init() }
func file_nevr_api_proto_init() {
	if File_nevr_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nevr_api_proto_rawDesc), len(file_nevr_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nevr_api_proto_goTypes,
		DependencyIndexes: file_nevr_api_proto_depIdxs,
		MessageInfos:      file_nevr_api_proto_msgTypes,
	}.Build()
	File_nevr_api_proto = out.File
	file_nevr_api_proto_goTypes = nil
	file_nevr_api_proto_depIdxs = nil
}
